import time

print("     ---------------------------------------------------------------------------------------------------------")
print("     |                                                                                                       |")
print("     |                                                                                                       |")
print("     |                 W E L C O M E    T O   T H E   A D V E N T U R E   G A M E                            |")
print("     |                                                                                                       |")
print("     |                                                                                                       |")
print("     ---------------------------------------------------------------------------------------------------------")
time.sleep(3)
print("You're an Adventurer, finding your way to the treasure which was hidden by some FAMOUS guy!\n")
time.sleep(3)
print("You have got no friends to go with so, you're all one on this adventure!!\n")
time.sleep(3)
print("Everyone would find the treasure right away if it was easy!!! \n")
time.sleep(3)
print("but......")
time.sleep(2)
print("There are different ways to that treasure, some of them lead to death and only one lead to the treasure!!\n\n")
print("So -------------------BEST OF LUCK-----------!!!!!!!")
time.sleep(6)
print("\n \n")
print("----------------------------------------------------------------")
time.sleep(0.5)
print("|    L E T   T H E   A D V E N T U R E    B E G I N !!!!!!!!!!-|")
time.sleep(0.5)
print("----------------------------------------------------------------")
time.sleep(5)
print("\n \n")
start = str.upper(input("Enter [G] to start the game :)\n  OR enter [Q] to quit!! \n---->"))
if start == 'G':
        print("You have two ways ahead of you.\n")
        time.sleep(1)
        way_1 = str.upper(input("-----Enter L to go left and R to go right \n -->"))
        if way_1 == 'R':
            print("walking the path .....\n")
            time.sleep(1)
            print(".........\n")
            time.sleep(2)
            print("Oh !you again found two pathways ...\n.")
            way_2 = str.upper(input("-----Enter L to go left and R to go right \n -->"))
            if way_2 == 'R':
                print("walks the path.....\n")
                time.sleep(2)
                print("oh no you've encountered a beast on your way !!!\n")
                time.sleep(2)
                fight = str.upper(input("Do you want to fight it through or not ? IF yes press 'Y' else press 'N'!!\n----->"))
                if fight == 'Y':
                    time.sleep(1)
                    print("Fighting...\n")
                    time.sleep(1)
                    print("after 1 hour of bloody fight you won and you're continuing your journey!!!\n")
                    time.sleep(2)
                    print("You've again encountered two ways !!\n")
                    way_3 = str.upper(input("-----Enter L to go left and R to go right \n -->"))
                    if way_3 == 'R':
                        time.sleep(0.5)
                        print("walks the path....\n")
                        time.sleep(2)
                        print("After walking for days and nights you have again encountered two ways---\n")
                        way_4 = str.upper(input("-----Enter L to go left and R to go right \n -->"))
                        if way_4 == 'R':
                            print("After all those walks you're now taking some rest!!!\n")
                            time.sleep(1)
                            print(".......")
                            time.sleep(1)
                            print("......")
                            time.sleep(2)
                            print(".....")
                            time.sleep(3)
                            print("...")
                            time.sleep(2)
                            print("You've now taken enough rest and now you're continuing your journey again!!!\n ")
                            time.sleep(1.5)
                            print("You encountered a mysterious door infront of you which need a key to enter...\n ")
                            time.sleep(2)
                            print("luckily! you found a riddle that leads to the key---\n")
                            time.sleep(1)
                            print("The riddle is... \n")
                            time.sleep(1)
                            print(" 9 = 54 \n 8 = 40 \n 7 = 28 \n 6 = 18 \n 5 = 10 \n 3 = ?\n")
                            time.sleep(2)
                            print("-----Find the correct value of 3 to enter the door\n")
                            ans = int(input("-----Your answer?\n ---->"))
                            if ans == int(0):
                                time.sleep(2)
                                print("Oouhhh! You're smart ... Correct answer!!\n")
                                time.sleep(1)
                                print("Gate opens....\n")
                                time.sleep(2)
                                print("After roaming around the place for sometime, you found two ways ----\n")
                                print("At your right and left.\n")
                                time.sleep(2)
                                way_5 = str.upper(input("-----Enter L to go left and R to go right \n -->"))
                                if way_5 == 'R' or way_5 == 'L':
                                    time.sleep(2)
                                    print("walks the path....\n")
                                    time.sleep(1)
                                    print("After walking for few hours you encountered a big wall. DEAD END!!!!\n")
                                    time.sleep(3)
                                    print("Y O U   L O S T !!!!!!\n")
                                    print("\n The game will automatically exit in 5 seconds....")
                                    time.sleep(5)
                                    exit()
                                else:
                                    time.sleep(1)
                                    print("----------------------Invalid input!!!--------------")
                                    time.sleep(5)
                                    exit()
                            else:
                                print("------------------wrong answer... \n BETTER LUCK NEXT TIME !!")
                                time.sleep(5)
                                exit()
                        elif way_4 == 'L':
                            time.sleep(2)
                            print("walks the path....\n")
                            print("after hours of walking you are in DEAD END!\n")
                            time.sleep(3)
                            print(" -----         YOU LOST           -----  \n")
                            time.sleep(2)
                            print("The game will automatically end in 5 seconds....\n")
                            time.sleep(5)
                            exit()
                        else:
                            print("--------------Invalid input-------------------\n")
                            time.sleep(5)
                            exit()
                    elif way_3 == 'L':
                        time.sleep(2)
                        print("walks the path...\n")
                        time.sleep(2)
                        print("After hours of walking...\n")
                        time.sleep(1)
                        print("You found two underway passages...\n")
                        time.sleep(1)
                        print("----LEFT and RIGHT!")
                        time.sleep(2)
                        pasg_way = str.upper(input("-----Enter L to go left and R to go right \n -->"))
                        if pasg_way == 'R':
                            time.sleep(2)
                            print("walks inside...\n")
                            time.sleep(1)
                            print("Unfortunately, you ended up in a HIGH MANA ZONE area !!!! \n")
                            time.sleep(2)
                            print("HIGH MANA ZONE ---> area where people with low stamina or endurance can't survive!\n")
                            print("Has tornados all around!\n")
                            print("can't see anything due to dust particles!\n")
                            time.sleep(5)
                            print("You've got 3 options!\n")
                            time.sleep(1)
                            print("\n [1]A horse \n [2]A Chopper [3]Nothing \n")
                            time.sleep(2)
                            anse = int(input("------Which one will you chose?\n --->"))
                            time.sleep(2)
                            if anse == 1 or anse == 2:
                                print("---------WRONG ANSWER! YOU ENDED UP DEAD!\n")
                                time.sleep(2)
                                print("---------------YOU LOST!!---------------------\n")
                                time.sleep(2)
                                print("The game will automatically end in 5 seconds....\n")
                                time.sleep(5)
                                exit()
                            elif anse == 3:
                                print("----------RIGHT ANSWER! YOU HAVE GOT GOOD STAMINA AND YOU ARE STRONG !!\n")
                                print("SO YOU NEED NOTHING!\n")
                                time.sleep(2)
                                print("walks through the HIGH MANA ZONE area...\n")
                                time.sleep(1)
                                print("takes some rest & sleep!\n")
                                time.sleep(2)
                                print("after that you again continue the journey!\n")
                                time.sleep(1)
                                print("You again found two ways.. LEFT AND RIGHT!\n")
                                time.sleep(1)
                                insd_way = str.upper(input("-----Enter L to go left and R to go right \n -->"))
                                time.sleep(2)
                                if insd_way == 'L':
                                    print("walks the path....\n")
                                    time.sleep(2)
                                    print("after hours of walking you ended up in a DEAD END!\n")
                                    time.sleep(1)
                                    print("------------------YOU LOST!!!----------------------")
                                    time.sleep(1)
                                    print("The game will automatically end in 5 seconds....\n")
                                    time.sleep(5)
                                    exit()
                                elif insd_way == 'R':
                                    print("walks the path....\n")
                                    time.sleep(2)
                                    print("after hours of walking you ended up in a DEAD END!\n")
                                    time.sleep(1)
                                    print("------------------------YOU LOST!!!----------------------\n")
                                    time.sleep(2)
                                    print("The game will automatically end in 5 seconds....\n")
                                    time.sleep(5)
                                    exit()
                                else:
                                    print("-------------------------------Invalid Input!----------------------\n")
                                    time.sleep(5)
                                    exit()
                        elif pasg_way == 'L':
                            print("walks the path...\n")
                            time.sleep(2)
                            print("Your way was blocked by a deep and strong wave river !\n")
                            time.sleep(2)
                            print("But....\n")
                            time.sleep(2)
                            print("There was boat but it also ha a riddle in it to be turned on..\n")
                            time.sleep(2)
                            print("The riddle was....\n")
                            time.sleep(2)
                            ans1 = int(input("\n ---> WHEN I WAS 14, MY SISTER WAS HALF OF MY AGE. NOW I AM 35, \n WHAT IS MY SISTER'S AGE?"))
                            if ans1 == int(28):
                                time.sleep(5)
                                print("------------You guessed it right!\n")
                                time.sleep(1)
                                print("Crosses the river with the boat.\n")
                                time.sleep(1)
                                print("After 2 days of walking you again found two ways LEF AND RIGHT!!\n")
                                time.sleep(2)
                                last_way = str.upper(input("-----Enter L to go left and R to go right \n -->"))
                                time.sleep(2)
                                if last_way == 'R':
                                    print("walks the path...\n")
                                    time.sleep(1)
                                    print("Ended up in a DEAD END\n")
                                    print("     -----          YOU LOST     -----         \n")
                                    time.sleep(2)
                                    print("The game will automatically end in 5 seconds...\n")
                                    time.sleep(5)
                                    exit()
                                elif last_way == 'L':
                                    print("walks the path....\n")
                                    time.sleep(2)
                                    print("Finds golds, silvers, coins on the way!\n")
                                    time.sleep(2)
                                    print("________________________________________________________________________________________")
                                    time.sleep(0.5)
                                    print("--------------------------CONGRATS! YOU FOUND THE TREASURE!!!---------------------------")
                                    time.sleep(0.5)
                                    print("________________________________________________________________________________________\n")
                                    time.sleep(3)
                                    print("-----------------------------------------------YOU WON----------------------------------------------\n")
                                    time.sleep(2)
                                    print("The game will automatically end in 20 seconds......\n")
                                    time.sleep(20)
                                    exit()
                                else:
                                    print("------------------------------Invalid input!!--------------------------------\n")
                                    time.sleep(5)
                                    exit()
                            else:
                                time.sleep(1)
                                print("--------------------------------WRONG ANSWER!!-------------------------------\n")
                                time.sleep(1)
                                print("YOU 'RE STUCK THERE FOREVER!    YOU LOST !!!!!!!!!\n")
                                time.sleep(2)
                                print("The game will automatically end in 5 seconds...\n")
                                time.sleep(5)
                                exit()
                        else:
                            time.sleep(1)
                            print("------------------------------------Invalid Input!!!----------------------------\n")
                            time.sleep(5)
                            exit()

                    else:
                        print("----------------------------------Invalid input!!!!!!--------------------------------\n")
                        time.sleep(5)
                        exit()

                elif fight == 'N':
                    print("The only way was to fight the beast to get to the target. \n       ------THE END\n")
                    print("\n")
                    time.sleep(1)
                    print("The game will automatically exit in 5 seconds...\n")
                    time.sleep(5)
                    exit()
                else:
                    print("-----------------------------------------Invalid Input!!!-------------------------------\n")
                    time.sleep(5)
                    exit()

            elif way_2 == 'L':
                time.sleep(2)
                print("walks the path...")
                time.sleep(2)
                print("you've been walking for now days....")
                time.sleep(3)
                print("On the 3rd day you see a mysterious Door with a lock in it.")
                time.sleep(2)
                print("After looking it for few minutes you found a riddle which lead to the key of the lock !!!")
                time.sleep(1)
                print("The riddle says.....")
                time.sleep(2)
                print(" 1 = 2 \n 2 = 5 \n 3 = 10 \n 4 = 17 \n 6 = 37 \n 8 = ? \n")
                time.sleep(5)
                an = int(input("Your answer? \n ---->"))
                if an == int(65):
                    time.sleep(2)
                    print("YOU GUESSED IT RIGHT !!")
                    time.sleep(1)
                    print("Door opens....")
                    time.sleep(2)
                    print("Found gold, silver, paintings etc.. but")
                    time.sleep(4)
                    print("The real treasure wasnt found yet..")
                    time.sleep(1)
                    print("Then you found two ways inside the place...")
                    time.sleep(1)
                    print("as always LEFT  and  RIGHT ---")
                    time.sleep(2)
                    inside_way1 = str.upper(input("enter L to go left and R to go right \n -->"))
                    if inside_way1 == 'R':
                        time.sleep(2)
                        print("After few days to journey you were in desert ")
                        time.sleep(1)
                        print("You were too exhausted and needed something to eat or drink!")
                        time.sleep(2)
                        print("Then you found a Hotel in the middle of the desert out of no where!")
                        time.sleep(1)
                        print("Your mind was blank so without thinking anything you went in and started eating ....")
                        time.sleep(2)
                        print("After eating.... ")
                        print("You ended up DEAD!!!")
                        time.sleep(2)
                        print("THE FOUND WAS POISONIOUS !! \n      YOU   LOST !!!!!!!")
                        time.sleep(2)
                        print(" The game will automatically exit in 5 seconds.....")
                        time.sleep(5)
                        exit()
                    elif inside_way1 == 'L':
                        time.sleep(2)
                        print("walks the passage...")
                        time.sleep(2)
                        print("You ended up in the middle of the forest and again found two ways....")
                        time.sleep(3)
                        print("LEFT AND RIGHT!!")
                        time.sleep(2)
                        ways = str.upper(input("enter L to go left and R to go right \n -->"))
                        if ways == 'R' or ways == 'L':
                            time.sleep(2)
                            print("YOU FIND YOURSELF IN A DEAD END !!! ")
                            time.sleep(1)
                            print(" WRONG WAY! YOU LOST!!!")
                            time.sleep(2)
                            print("The game will automatically end in 5 seconds...")
                            time.sleep(5)
                            exit()
                    else:
                        time.sleep(2)
                        print("Invalid Input!!!")
                        time.sleep(5)
                        exit()
                else:
                    time.sleep(2)
                    print("WRONG ANSWER!!")
                    time.sleep(1)
                    print("The game will automatically exit in 5 seconds....")
                    time.sleep(5)
                    exit()
            else:
                print("-----------------------------------------Invalid input!!!!-----------------------------------\n")

        elif way_1 == 'L':
            time.sleep(2)
            print("walks the path....\n")
            time.sleep(2)
            print("After some time he finds two roads.\n")
            time.sleep(2)
            print("----------------LEFT AND RIGHT!-----------------")
            time.sleep(2)
            in_way_1 = str.upper(input("-----Enter L to go left and R to go right \n -->"))
            time.sleep(2)
            if in_way_1 == 'L':
                print("walks the path...\n")
                time.sleep(3)
                print("After walking for some time you found a beast in your way!\n")
                time.sleep(2)
                print("(BEAST ROARS-- at you !!)\n")
                time.sleep(2)
                print("Do you want to fight the beast or run away like a child?\n")
                time.sleep(2)
                yr_ans = str.upper(input("Y/N ?\n--->"))
                time.sleep(2)
                if yr_ans == 'Y':
                    print("Fighting with the BEAST!....\n")
                    time.sleep(3)
                    print(".......")
                    time.sleep(2)
                    print("You defeated the beast and you again find yourself in a two way road!\n")
                    time.sleep(3)
                    print("As always, LEFT or RIGHT?\n")
                    time.sleep(1)
                    ins_way_1 = str.upper(input("-----Enter L to go left and R to go right \n -->"))
                    time.sleep(3)
                    if ins_way_1 == 'L':
                        print("walks the path....\n")
                        time.sleep(2)
                        print("You now encountered a door that seem mysterious but need a key to open!\n")
                        time.sleep(1)
                        print("looks around the place...\n")
                        time.sleep(2)
                        print(". \n.\n.\n.")
                        time.sleep(2)
                        print("after looking around for sometime, you found a riddel that may lead you to the key!\n")
                        time.sleep(1)
                        print("The riddle is.....")
                        time.sleep(2)
                        print(" 6 / 4 = 210 \n 9 / 2 = 711 \n 8 / 5 = 313 \n 5 / 2 = 37 \n 7 / 6 = ?\n")
                        time.sleep(6)
                        yr_answer = int(input("Your answer?\n--->"))
                        time.sleep(2)
                        if yr_answer == int(113):
                            print("--------------------CORRECT ANSWER!------------------")
                            time.sleep(2)
                            print("The key to the door was 113, and now you're entering the door!\n")
                            time.sleep(2)
                            print("You again encounter a two way round behind the door\n")
                            time.sleep(2)
                            print("LEFT OR RIGHT!!!\n")
                            time.sleep(3)
                            ins_way_2 = str.upper(input("-----Enter L to go left and R to go right \n -->"))
                            time.sleep(2)
                            if ins_way_2 == 'R' or ins_way_2 == 'L':
                                time.sleep(2)
                                print("walks the path....\n")
                                time.sleep(1)
                                print("After walking for few hours you encountered a big wall. DEAD END!!!!\n")
                                time.sleep(3)
                                print("---------------------------Y O U   L O S T !!!!!!-----------------------\n")
                                print("\n The game will automatically exit in 5 seconds....\n")
                                time.sleep(5)
                                exit()
                            else:
                                time.sleep(1)
                                print("--------------------------------------Invalid input!!!------------------------")
                                time.sleep(5)
                                exit()

                        else:
                            print("------------------------------Wrong answer!!!-----------------------\n")
                            time.sleep(1)
                            print("------------------------------YOU LOST!!!---------------------------\n")
                            time.sleep(2)
                            print("The game will automatically end in 5 seconds...\n")
                            time.sleep(5)
                            exit()
                    elif ins_way_1 == 'R':
                        print("walks the path....\n")
                        time.sleep(2)
                        print("After a long walk you found a mysterious door with a lock in it!\n")
                        time.sleep(2)
                        print("You looked around for few minutes and found a riddle which leads to the key to the door.\n")
                        time.sleep(2)
                        print("The riddle is ....")
                        time.sleep(2)
                        print(" 9 + 2 = 711 \n 14 + 6 = 820 \n 17 + 11 = 628 \n 12 + 3 = ?\n")
                        time.sleep(5)
                        m_ans = int(input("-----Your answer?!\n---->"))
                        if m_ans == int(915):
                            time.sleep(2)
                            print("The door opens!\n")
                            time.sleep(2)
                            print("Inside the door you found to ways. RIGHT AND LEFT!\n")
                            time.sleep(2)
                            way_in = str.upper(input("-----Enter L to go left and R to go right \n -->"))
                            time.sleep(3)
                            if way_in == 'L':
                                print("walks the path....\n")
                                time.sleep(2)
                                print("...")
                                time.sleep(1)
                                print("still walking.. .\n")
                                time.sleep(2)
                                print("Found two way road.\n")
                                time.sleep(1)
                                print('LEFT and RIGHT!\n')
                                time.sleep(2)
                                way__ = str.upper(input("-----Enter L to go left and R to go right \n -->"))
                                time.sleep(2)
                                if way__ == 'R' or way__ == 'L':
                                    print("walks the path...\n")
                                    time.sleep(2)
                                    print("Found yourself in a dead end!!\n")
                                    time.sleep(2)
                                    print("----------------------------------YOU LOST!-------------------------------\n")
                                    time.sleep(1)
                                    print("The game will automatically end in 5 seconds...\n")
                                    time.sleep(5)
                                    exit()
                                else:
                                    print("---------------------------------Invalid input!!!------------------------\n")
                                    time.sleep(5)
                                    exit()
                            elif way_in == 'R':
                                print("walks the path...\n")
                                time.sleep(2)
                                print("......")
                                time.sleep(1)
                                print("Still walking...\n")
                                time.sleep(1)
                                print("After a long waay around you found yourself in a DEAD END!\n")
                                time.sleep(2)
                                print("-------------------------------------- YOU LOST!!!---------------------------\n")
                                time.sleep(2)
                                print("The game will automatically end in 5 seconds....\n")
                                time.sleep(5)
                                exit()
                            else:
                                print("-------------------------------------Invalid input!!!-------------------------\n")
                                time.sleep(5)
                                exit()
                        else:
                            time.sleep(2)
                            print("---------------------------------------WRONG ANSWER!!!!----------------------------------\n")
                            time.sleep(2)
                            print("---------------------------------------YOU LOST!!!---------------------------------------\n")
                            time.sleep(1)
                            print("The game will automatically end in 5 seconds....\n")
                            time.sleep(5)
                            exit()
                    else:
                        print("-------------------------------------Invalid input!!!--------------------------------------\n")
                        time.sleep(5)
                        exit()
                elif yr_ans == 'N':
                    print("The only way around was to beat the BEAST.\n")
                    time.sleep(2)
                    print("--------------------------------------YOU LOST!!------------------------------")
                    time.sleep(2)
                    print("The game will automatically end in 5 seconds...\n")
                    time.sleep(5)
                    exit()
                else:
                    print("--------------------------------------Invalid input!--------------------------------")
                    time.sleep(5)
                    exit()

            elif in_way_1 == 'R':
                print("walks the path....\n")
                time.sleep(3)
                print("You are now travelling for days and couldnt find anything but...\n")
                time.sleep(2)
                print("At the 3rd day you found two way road. LEFT AND RIGHT!\n")
                time.sleep(2)
                i_way1 = str.upper(input("-----Enter L to go left and R to go right \n -->"))
                if i_way1 == 'L' or i_way1 == 'R':
                    time.sleep(2)
                    print("OOPS!!\n")
                    time.sleep(2)
                    print("Unfortunately you an into a dead end!\n")
                    time.sleep(1)
                    print("-----------------------------------YOU LOST !!!-----------------------------\n")
                    time.sleep(2)
                    print("The game will automatically end in 5 seconds....\n")
                    time.sleep(5)
                    exit()
                else:
                    time.sleep(1)
                    print("--------------------------------------Invalid input!!----------------------------------\n")
                    time.sleep(2)
                    print("exiting the game in 5....")
                    time.sleep(5)
                    exit()
            else:
                print("------------------------------------------Invalid input!!-------------------------------------")
                time.sleep(5)
                exit()
        else:
            print("-------------------------------------Invalid input!!---------------------------------")
elif start == 'Q':
    print(" -----Too shame that you gave up without even trying :(( .... HOPE you'll start again sometime\n")
    time.sleep(2)
    print("The game will exit in 5....\n")
    time.sleep(5)
    exit()
else:
    print("-----Invalid input please enter 'G' to start and 'Q' to quit. Please restart the game to play again!")


